// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  firebase: {
    projectId: 'pruebaangularjesusjuarez',
    appId: '1:782389252415:web:a9284f14c66a5a4feec38a',
    storageBucket: 'pruebaangularjesusjuarez.appspot.com',
    apiKey: 'AIzaSyBAT1dGaFswb2_f1ssgCMnivyDBOQ6J1cM',
    authDomain: 'pruebaangularjesusjuarez.firebaseapp.com',
    messagingSenderId: '782389252415',
    measurementId: 'G-4RCBDJ2BFN',
  },
  production: true,
  version: env['npm_package_version'],
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],
};
